import "./globals.css";
import { Quicksand, Kaushan_Script } from "next/font/google";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
  display: "swap",
});

const kaushan = Kaushan_Script({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-kaushan",
  display: "swap",
});

export const metadata = {
  title: "Bonne Sante",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${quicksand.className} ${kaushan.variable}`}>
      <body>{children}</body>
    </html>
  );
}
